import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import MobileSidebar from "@/components/MobileSidebar";

const SFMono = localFont({
  src: [{ path: "../assets/fonts/SFMono-Regular.otf", weight: "400" }],
  variable: "--font-SFMono",
});

const SFDisplay = localFont({
  src: [
    { path: "../assets/fonts/SF-Pro-Display-Regular.otf", weight: "400" },
    { path: "../assets/fonts/SF-Pro-Display-Semibold.otf", weight: "600" },
  ],
  variable: "--font-SFDisplay",
});

export const metadata: Metadata = {
  title: "Vinícius Bastos - Portfólio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={`${SFMono.variable} ${SFDisplay.variable}`}>
      <body>
        <SidebarProvider>
          <Header />
          {children}
        </SidebarProvider>
        <Footer />
      </body>
    </html>
  );
}
